### ISSUE TITLE
Is it possible to use it without redis?

### ISSUE THREAD

**Issue by antback** [qbhy/hyperf-auth#24]
Hi

I would like to know if it is possible to use it without redis. I get the following error:

```
[ERROR] Connection refused[246] in /opt/www/vendor/hyperf/redis/src/RedisConnection.php
[ERROR] #0 /opt/www/vendor/hyperf/redis/src/RedisConnection.php(246): Redis->connect()
#1 /opt/www/vendor/hyperf/redis/src/RedisConnection.php(116): Hyperf\Redis\RedisConnection->createRedis()
#2 /opt/www/vendor/hyperf/redis/src/RedisConnection.php(70): Hyperf\Redis\RedisConnection->reconnect()
#3 /opt/www/vendor/hyperf/redis/src/Pool/RedisPool.php(58): Hyperf\Redis\RedisConnection->__construct()
#4 /opt/www/vendor/hyperf/pool/src/Pool.php(167): Hyperf\Redis\Pool\RedisPool->createConnection()
#5 /opt/www/vendor/hyperf/pool/src/Pool.php(60): Hyperf\Pool\Pool->getConnection()
#6 /opt/www/runtime/container/proxy/Hyperf_Redis_Redis.proxy.php(92): Hyperf\Pool\Pool->get()
#7 /opt/www/runtime/container/proxy/Hyperf_Redis_Redis.proxy.php(45): Hyperf\Redis\Redis->getConnection()
#8 /opt/www/vendor/hyperf/di/src/Aop/ProceedingJoinPoint.php(84): Hyperf\Redis\Redis->Hyperf\Redis\{closure}()
#9 /opt/www/vendor/hyperf/di/src/Aop/ProxyTrait.php(85): Hyperf\Di\Aop\ProceedingJoinPoint->processOriginalMethod()
#10 /opt/www/vendor/hyperf/utils/src/Pipeline.php(104): Hyperf\Redis\Redis::Hyperf\Di\Aop\{closure}()
#11 /opt/www/vendor/hyperf/di/src/Aop/ProceedingJoinPoint.php(69): Hyperf\Utils\Pipeline::Hyperf\Utils\{closure}()
#12 /opt/www/vendor/hyperf/tracer/src/Aspect/RedisAspect.php(71): Hyperf\Di\Aop\ProceedingJoinPoint->process()
#13 /opt/www/vendor/hyperf/di/src/Aop/Pipeline.php(30): Hyperf\Tracer\Aspect\RedisAspect->process()
#14 /opt/www/vendor/hyperf/utils/src/Pipeline.php(95): Hyperf\Di\Aop\Pipeline->Hyperf\Di\Aop\{closure}()
#15 /opt/www/vendor/hyperf/di/src/Aop/ProxyTrait.php(86): Hyperf\Utils\Pipeline->then()
#16 /opt/www/vendor/hyperf/di/src/Aop/ProxyTrait.php(29): Hyperf\Redis\Redis::handleAround()
#17 /opt/www/runtime/container/proxy/Hyperf_Redis_Redis.proxy.php(70): Hyperf\Redis\Redis::__proxyCall()
#18 /opt/www/vendor/hyperf/redis/src/RedisProxy.php(32): Hyperf\Redis\Redis->__call()
#19 /opt/www/vendor/hyperf/model-cache/src/Handler/RedisHandler.php(132): Hyperf\Redis\RedisProxy->__call()
#20 /opt/www/vendor/hyperf/model-cache/src/Manager.php(190): Hyperf\ModelCache\Handler\RedisHandler->deleteMultiple()
#21 /opt/www/vendor/hyperf/model-cache/src/Cacheable.php(60): Hyperf\ModelCache\Manager->destroy()
#22 /opt/www/vendor/hyperf/model-cache/src/Listener/DeleteCacheListener.php(47): App\Model\Model->deleteCache()
#23 /opt/www/vendor/hyperf/event/src/EventDispatcher.php(48): Hyperf\ModelCache\Listener\DeleteCacheListener->process()
#24 /opt/www/vendor/hyperf/database/src/Model/Concerns/HasEvents.php(150): Hyperf\Event\EventDispatcher->dispatch()
#25 /opt/www/vendor/hyperf/database/src/Model/Model.php(1316): Hyperf\Database\Model\Model->fireModelEvent()
#26 /opt/www/vendor/hyperf/database/src/Model/Model.php(591): Hyperf\Database\Model\Model->finishSave()
#27 /opt/www/runtime/container/proxy/App_Controller_AuthController.proxy.php(78): Hyperf\Database\Model\Model->save()
#28 /opt/www/vendor/hyperf/http-server/src/CoreMiddleware.php(161): App\Controller\AuthController->regist()
#29 /opt/www/vendor/hyperf/http-server/src/CoreMiddleware.php(113): Hyperf\HttpServer\CoreMiddleware->handleFound()
#30 /opt/www/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\HttpServer\CoreMiddleware->process()
#31 /opt/www/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest()
#32 /opt/www/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\Dispatcher\HttpRequestHandler->handle()
#33 /opt/www/vendor/hyperf/http-server/src/Server.php(117): Hyperf\Dispatcher\HttpDispatcher->dispatch()
#34 {main}
```

Even when I have in the configuration:

```
            'cache' => new \Doctrine\Common\Cache\FilesystemCache(sys_get_temp_dir()),
              // If you need distributed deployment, please choose redis or other cache drivers that support distributed
              // 'cache' => function () {
              // return make(\Qbhy\HyperfAuth\HyperfRedisCache::class);
              // },
```

Thanks  for your help!

**Comment by antback** [comment]
Don't worry, it seems that is because the usage of Cacheable.

Thanks.
